baseURL = 'https://mingzefei.github.io'
languageCode = 'en-us'
theme = 'mainroad'
# theme = 'hugo-book'

hasCJKLanguage = true # To make summary displays correctly
publishDir = 'public' # Incase the default public dir change
DefaultContentLanguage = 'zh-cn'

[Languages]
  [Languages.zh-cn]
    title = "明泽飞's Blog"
    # subtitle = "泽飞's Blog"
    contentDir = '/zh-cn'
    languageName = '简体中文'
    weight = 1
  [Languages.zh-cn.menu]
    [[Languages.zh-cn.menu.main]]
      identifier = 'gohome'
      name = '首页'
      url = '/'
      weight = 101
    [[Languages.zh-cn.menu.main]]
      identifier = 'goblog'
      name = '日志'
      url = '/zh-cn/posts'
      weight = 102
    [[Languages.zh-cn.menu.main]]
      identifier = 'goabout'
      name = '关于'
      url = '/about.md'
      weight = 103
    [[Languages.zh-cn.menu.main]]
      identifier = 'gocv'
      name = '简历'
      url = '/my_cv.md'
      weight = 104
#     [[Languages.zh-cn.menu.main]]
#       identifier = 'issues-cn'
#       name = '留言'
#       url = 'https://github.com/Mingzefei/Mingzefei.github.io/issues'
#       weight = 105
    [[Languages.zh-cn.menu.main]]
      identifier = 'goen'
      name = 'English'
      url = '/en'
      weight = 106
  [Languages.zh-cn.Author]
    name = '明泽飞'
    # bio = ''
    # avatar = ''

  [Languages.en]
    title = "Ming zefei's Blog"
    # subtitle = "zefei's Blog"
    contentDir = '/en'
    languageName = 'English'
    weight = 2
  [Languages.en.menu]
    [[Languages.en.menu.main]]
      identifier = 'gohome'
      name = 'home'
      url = '/'
      weight = 101
    [[Languages.en.menu.main]]
      identifier = 'goblog'
      name = 'blog'
      url = '/en/posts'
      weight = 102
    [[Languages.en.menu.main]]
      identifier = 'goabout'
      name = 'about'
      url = '/en/about.md'
      weight = 103
    [[Languages.en.menu.main]]
      identifier = 'gocv'
      name = 'vitae'
      url = '/en/my_cv.md'
      weight = 104
#     [[Languages.en.menu.main]]
#       identifier = 'issues-cn'
#       name = 'message'
#       url = 'https://github.com/Mingzefei/Mingzefei.github.io/issues'
#       weight = 105
    [[Languages.en.menu.main]]
      identifier = 'gocn'
      name = '中文'
      url = '/zh-cn'
      weight = 106
  [Languages.en.Author]
    name = 'Mingzefei'
    # bio = ''
    # avatar = ''

[Params]
  description = "Mingzefei's Personal blog"
  copyright = 'HUA guangbin'
  toc = true # Enable Table of Contents
  mathjax = true
  post_meta = ['date','categories','translations'] # Order of post meta information
  mainSection = ['posts']
  highlightColor = '#224298' # default #e22d30
  [Params.sidebar]
    home = 'right'
    widgets = ['search','categories','recent','taglist','social']
  # [Params.widgets]
  #   [Params.widgets.search]
  #     url = "/search/"
  #     input.name = false
  #     input.pre = ""

